CREATE TABLE PESSOA_FISICA
(
	CD_PESSOA_FISICA	INT IDENTITY(1,1) PRIMARY KEY,
	NM_PESSOA_FISICA	VARCHAR(500) NOT NULL,
	DT_NASCIMENTO		DATETIME NOT NULL,
	DS_EMAIL			VARCHAR(50) NOT NULL,	
	NR_CPF				VARCHAR(11) NULL,
	DS_SENHA			VARCHAR(200) NOT NULL,
	IE_ATIVO			BIT NOT NULL DEFAULT 1,
	DT_ATUALIZACAO		DATETIME NOT NULL
)

CREATE TABLE MEDICO
(
	CD_MEDICO			INT IDENTITY(1,1) PRIMARY KEY,
	CRM_MEDICO			VARCHAR(50) NOT NULL,
	CD_PESSOA_FISICA	INT NOT NULL FOREIGN KEY REFERENCES PESSOA_FISICA(CD_PESSOA_FISICA),
	NM_GUERRA			VARCHAR(500) NOT NULL,
	DS_EMAIL			VARCHAR(50) NOT NULL,	
	DS_SENHA			VARCHAR(200) NOT NULL,
	IE_ATIVO			BIT NOT NULL DEFAULT 1,
	DT_ATUALIZACAO		DATETIME NOT NULL
)

CREATE TABLE TIPO_ATENDIMENTO
(
	ID_TIPO_ATENDIMENTO	INT IDENTITY(1,1) PRIMARY KEY,
	DS_TIPO_ATENDIMENTO	VARCHAR(30) NOT NULL,
	IE_ATIVO			BIT NOT NULL DEFAULT 1,
	DT_ATUALIZACAO		DATETIME NOT NULL
)

CREATE TABLE ESPECIALIDADE_ATENDIMENTO
(
	ID_ESPECIALIDADE	INT IDENTITY(1,1) PRIMARY KEY,
	DS_ESPECIALIDADE	VARCHAR(100),
	IE_ATIVO			BIT NOT NULL DEFAULT 1,
	DT_ATUALIZACAO		DATETIME NOT NULL
)

CREATE TABLE ATENDIMENTO_PACIENTE
(
	NR_ATENDIMENTO		INT IDENTITY(1,1) PRIMARY KEY,
	CD_PESSOA_FISICA	INT NOT NULL FOREIGN KEY REFERENCES PESSOA_FISICA(CD_PESSOA_FISICA),
	CD_MEDICO			INT NOT NULL FOREIGN KEY REFERENCES MEDICO(CD_MEDICO),
	ID_TIPO_ATENDIMENTO	INT NOT NULL FOREIGN KEY REFERENCES TIPO_ATENDIMENTO(ID_TIPO_ATENDIMENTO),
	ID_ESPECIALIDADE	INT NULL FOREIGN KEY REFERENCES ESPECIALIDADE_ATENDIMENTO(ID_ESPECIALIDADE),
	DT_ATENDIMENTO		DATETIME NOT NULL,
	CD_TOKEN			VARCHAR(15) NULL,
	
	DS_SINTOMA			VARCHAR(600) NULL,
	DS_DIAGNOSTICO		VARCHAR(600) NULL,
	DS_PRESCRICAO		VARCHAR(600) NULL,
	DS_OBSERVACAO		VARCHAR(600) NULL,
	
	IE_ATIVO			BIT NOT NULL DEFAULT 1,
	DT_ATUALIZACAO		DATETIME NOT NULL
)

CREATE TABLE TOKEN_ATENDIMENTO
(
	ID_TOKEN_ATENDIMENTO	INT IDENTITY(1,1) PRIMARY KEY,
	NR_ATENDIMENTO			INT NOT NULL FOREIGN KEY REFERENCES ATENDIMENTO_PACIENTE(NR_ATENDIMENTO),
	
	CD_TOKEN				VARCHAR(15) NOT NULL,

	DT_CRIACAO				DATETIME NOT NULL,
	DT_EXPIRACAO			DATETIME NOT NULL,
	DT_CONFIRMACAO			DATETIME NULL,
	
	IE_ATIVO				BIT NOT NULL DEFAULT 1,
	DT_ATUALIZACAO			DATETIME NOT NULL
)


