USE [ProntuarioUnico]
GO

/****** Object:  View [dbo].[PRONTUARIO]    Script Date: 02/12/2019 22:45:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[PRONTUARIO]
AS
SELECT 
	AP.NR_ATENDIMENTO, 
	AP.CD_PESSOA_FISICA, 
	TA.DS_TIPO_ATENDIMENTO, 
	AP.DT_ATENDIMENTO, 
	M.CD_MEDICO,
	M.CRM_MEDICO, 
	M.NM_GUERRA AS NM_MEDICO, 
	EA.DS_ESPECIALIDADE, 
	AP.DS_OBSERVACAO,
	AP.ID_TIPO_ATENDIMENTO,
	AP.ID_ESPECIALIDADE,
	AP.DS_SINTOMA,
	AP.DS_DIAGNOSTICO,
	AP.DS_PRESCRICAO
FROM            
				dbo.TOKEN_ATENDIMENTO			AS TOA
	INNER JOIN	dbo.ATENDIMENTO_PACIENTE		AS AP	ON	TOA.NR_ATENDIMENTO		= AP.NR_ATENDIMENTO 
														AND TOA.CD_TOKEN				= AP.CD_TOKEN
	INNER JOIN	dbo.MEDICO						AS M	ON	AP.CD_MEDICO			= M.CD_MEDICO 
	INNER JOIN	dbo.TIPO_ATENDIMENTO			AS TA	ON	AP.ID_TIPO_ATENDIMENTO	= TA.ID_TIPO_ATENDIMENTO 
	INNER JOIN	dbo.ESPECIALIDADE_ATENDIMENTO	AS EA	ON	AP.ID_ESPECIALIDADE		= EA.ID_ESPECIALIDADE
GO